travis:
  secure:
    BINSTAR_TOKEN: cee/ggYhrBD8FzVGyO6zy/3YS8yoj675sGUfIk6B4eF3vRsyX9BCgbcFVdQ5W+pP2j50YgoiTC/iQ8+rTyi99f5DhbnWtA6nGkcY4uhfh/Eq7QS2RTUkHG6sbcb9fKtJCyTV2e8KJLcev0Qv/OiOUaQpkRuEyWTZBHrkZtb2lp8k/T2S2CqGkZi1P11EfX2X5EnML1rSkhelaBYgWgYU8rPuU4MPlROVQr7oe0nrEPIogDPIm70eosAB2jh0cg6PgrHBmh3/XmF9RlnBq0i4LW4Uaia6Tcwbw/xg8T5Fe2bRTepbtowcVbUP46rbGbwHgSdfIDUL31AZQ3PBvm8D8A85nFDbn6zQHSt9+eBH11cYIr0PYg2cbPxaGaLtr3OcrxZymX7TGaL3fMp1PnhCI0cj2VcAm5kYyExbQVJEybrstEu3qINqgH0/4FAfQekjRJEmgA0l2iy4+ome81eSoncLa6rt8eZX49HOGv/1zFgT5yv5UleGRZF8QcjzI/xdbdeV0lp/Yv24i/cVI/by52YenoZs6GbCiS7L6LbUocEFFolF2W5PtyVvkcgf3BinGmG2J6arU2Bs8VOQ2ApmxNOInlkSJl3oJ6ao6q87TfUJ5V7/u7FmRNqVKFyYWmCdOMjLnRQuZZHu6Qzy4oyGJmjfw5hAC9e1keuX/RvF2mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
