travis:
  secure:
    BINSTAR_TOKEN: rf04d6t+lgDIoVDaPS7pWyX2MWpIg3Yng/LCrVp0UrALGH58fbG/68BSdqusD3sNLeT/wfxqtUG8W9Jy76iJa4/XT7fsqGwvq81QHnEVGCoosTNtYgKmmFMgJYn23dkPBOH1OW+xLeHhRr40Jqr3gMwJOwNvhgiEVyYU5d9mZ2wN7MsffSy7V8pSrypAVHT/rnHARtvxH9I3wZIqxVJe8hKQpPN9N6yGmxDcC4Jdm2cVQLHYGP26sweyCTJzaafQt2J2f1+VOGXU/jzzRmpD1r3ncLo1MqBdT38hifBdKxpFQFS15DpiJlZsosf+b8Xli+e+B7TApbGXwcos3sM68bAHF5pi5CnO51IAoyPBt8POqgN0HwV65bEk5WEEHA4E+5Uugx1yW5Va/YKFAL6bvXwLSXTbxQQHPqzl5wmqQ7H3jc7Qrx3C00tsSEFbcNEx/aL4EEeQHXg16ug0m4NeO5EY3k0XdJimcOYpwHOzlQiosZI9eEf78yXPz5CSTGXtCojrO/b+0JyqW+ErAO1RuehpJE8mqsftp07uesgetTlX+9JnWgJf9vVviNfyUmUv3xDJ+MiVUX/G1NmQnD/BAa4DXIIlbfFXpx+572iCGi/3DSxDde5+BfI2/2RTQY50F9Qrr7LqIGBdTJ/O8WCMgg5LQZ9vK0j0ojpgSQHGtI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
